### ISSUE TITLE
Mi band 4 -battery status is not visible

### ISSUE THREAD

**Issue by maxiges** [jefoce/xmi#2]
After loading watch faces to mi band battery status is not visible , icon and value

**Comment by nivin-studio** [comment]
The same question

**Comment by jefoce** [comment]
> After loading watch faces to mi band battery status is not visible , icon and value

Thanks, try new version

**Comment by nivin-studio** [comment]
> > After loading watch faces to mi band battery status is not visible , icon and value
> 
> Thanks, try new version

Still not

**Comment by jefoce** [comment]
> 
> 
> > > After loading watch faces to mi band battery status is not visible , icon and value
> > 
> > 
> > Thanks, try new version
> 
> Still not

Send WF file to my [email](mailto:jefoce23@gmail.com)

**Comment by jefoce** [comment]
**Works fine**
![xmi-watch](https://user-images.githubusercontent.com/33602561/102329994-b25a4400-3f91-11eb-9332-f93b0ca2671d.gif)

**Comment by maxiges** [comment]
Still is this problem 
![IMG_20201216_111259](https://user-images.githubusercontent.com/19745643/102335443-357a9a80-3f90-11eb-85e0-1c776d938ed9.jpg)  vs after loading watchface to miband 4 
![IMG_20201216_111522](https://user-images.githubusercontent.com/19745643/102335530-57741d00-3f90-11eb-8119-f06c3989d421.jpg)
  I an using notify and fitness to upload watchface 
![IMG_20201216_111901](https://user-images.githubusercontent.com/19745643/102335743-973b0480-3f90-11eb-9a4a-dbdbfaffd7bb.jpg)

**Comment by jefoce** [comment]
> 
> 
> Still is this problem
> ![IMG_20201216_111259](https://user-images.githubusercontent.com/19745643/102335443-357a9a80-3f90-11eb-85e0-1c776d938ed9.jpg) vs after loading watchface to miband 4
> ![IMG_20201216_111522](https://user-images.githubusercontent.com/19745643/102335530-57741d00-3f90-11eb-8119-f06c3989d421.jpg)
> I an using notify and fitness to upload watchface
> ![IMG_20201216_111901](https://user-images.githubusercontent.com/19745643/102335743-973b0480-3f90-11eb-9a4a-dbdbfaffd7bb.jpg)

Attach this WF file

**Comment by jefoce** [comment]
WF must contain 9 icons for every percentage step
![xmi-watch-2](https://user-images.githubusercontent.com/33602561/102339723-43371c80-3f9e-11eb-973a-388fbe6d8c13.gif)

**Comment by maxiges** [comment]
You show my project (bin file) that work correctly. I have problem on new watch face/. It is look similar but with christmas elements . I i sended to you two bin files one that work correctly make by different tool 1 year ago and new maid by your program.
on bin file generated by your tool after loading watch face to miband 4 is not show battery status.
![image](https://user-images.githubusercontent.com/19745643/102343538-fdc52000-3f9a-11eb-9154-907de0816ce7.png)

**Comment by jefoce** [comment]
Try, if it'll fix i'll create new update

[maxiMiband4_V4_MB4_christBatt_3_1_packed.zip](https://github.com/jefoce/xmi/files/5702403/maxiMiband4_V4_MB4_christBatt_3_1_packed.zip)

**Comment by maxiges** [comment]
Now work. Thank you so much 👍👍

**Comment by jefoce** [comment]
New version with fix loaded😉
