### ISSUE TITLE
for learning more

### ISSUE THREAD

**Issue by joelianruntu** [jefoce/xmi#4]
hi, i had made some watch faces before and here found ur great tool. I am so curious about how the tool makes .json and images become a .bin file. I started to learn programming several month ago and want to try something interesting. Would u like to tell me how the tool works? thx very much!

**Comment by jefoce** [comment]
Hi, i used another tool for packing .bin files, here https://amazfitwatchfaces.com/forum/viewtopic.php?f=29&t=720
